# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-05 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ISBN', models.CharField(max_length=100, unique=True)),
                ('publication_date', models.DateField(null=True)),
                ('cover', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('category', models.CharField(choices=[('GOT', 'Gothic'), ('SCI', 'Science'), ('ROM', 'Romance'), ('HIS', 'Historical'), ('SAG', 'Saga'), ('COM', 'Comic'), ('PYS', 'Psychological'), ('HOR', 'Horror'), ('FIC', 'Fiction'), ('FAN', 'Fantasy'), ('CRM', 'Crime'), ('POL', 'Political'), ('ADV', 'Adventure'), ('ACC', 'Action'), ('THR', 'Thriller')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
        ),
    ]
