# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-06 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20170505_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_book', to='authors.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('PYS', 'Psychological'), ('HIS', 'Historical'), ('ACC', 'Action'), ('SCI', 'Science'), ('GOT', 'Gothic'), ('ROM', 'Romance'), ('COM', 'Comic'), ('FIC', 'Fiction'), ('THR', 'Thriller'), ('FAN', 'Fantasy'), ('POL', 'Political'), ('ADV', 'Adventure'), ('CRM', 'Crime'), ('SAG', 'Saga'), ('HOR', 'Horror')], max_length=100),
        ),
    ]
