# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-06 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20170506_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_books', to='authors.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('ADV', 'Adventure'), ('THR', 'Thriller'), ('POL', 'Political'), ('SCI', 'Science'), ('HOR', 'Horror'), ('FIC', 'Fiction'), ('CRM', 'Crime'), ('ACC', 'Action'), ('FAN', 'Fantasy'), ('HIS', 'Historical'), ('PYS', 'Psychological'), ('ROM', 'Romance'), ('SAG', 'Saga'), ('GOT', 'Gothic'), ('COM', 'Comic')], max_length=100),
        ),
        migrations.AlterField(
            model_name='comments',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_book', to='books.Book'),
        ),
    ]
