# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-06 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20170506_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='usuario',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('HIS', 'Historical'), ('ADV', 'Adventure'), ('SAG', 'Saga'), ('GOT', 'Gothic'), ('SCI', 'Science'), ('POL', 'Political'), ('FAN', 'Fantasy'), ('CRM', 'Crime'), ('ACC', 'Action'), ('PYS', 'Psychological'), ('ROM', 'Romance'), ('COM', 'Comic'), ('HOR', 'Horror'), ('FIC', 'Fiction'), ('THR', 'Thriller')], max_length=100),
        ),
        migrations.AlterField(
            model_name='comments',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_comments', to='books.Book'),
        ),
    ]
