# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-06 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20170506_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('HOR', 'Horror'), ('GOT', 'Gothic'), ('PYS', 'Psychological'), ('THR', 'Thriller'), ('ROM', 'Romance'), ('COM', 'Comic'), ('SCI', 'Science'), ('ACC', 'Action'), ('POL', 'Political'), ('FIC', 'Fiction'), ('ADV', 'Adventure'), ('HIS', 'Historical'), ('CRM', 'Crime'), ('SAG', 'Saga'), ('FAN', 'Fantasy')], max_length=100),
        ),
    ]
