# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20170506_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('ROM', 'Romance'), ('PYS', 'Psychological'), ('HIS', 'Historical'), ('THR', 'Thriller'), ('CRM', 'Crime'), ('SAG', 'Saga'), ('FIC', 'Fiction'), ('ADV', 'Adventure'), ('GOT', 'Gothic'), ('SCI', 'Science'), ('COM', 'Comic'), ('HOR', 'Horror'), ('FAN', 'Fantasy'), ('POL', 'Political'), ('ACC', 'Action')], max_length=100),
        ),
    ]
