# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-05 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('sex', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=16)),
                ('category', models.CharField(choices=[('GOT', 'Gothic'), ('SCI', 'Science'), ('ROM', 'Romance'), ('HIS', 'Historical'), ('SAG', 'Saga'), ('COM', 'Comic'), ('PYS', 'Psychological'), ('HOR', 'Horror'), ('FIC', 'Fiction'), ('FAN', 'Fantasy'), ('CRM', 'Crime'), ('POL', 'Political'), ('ADV', 'Adventure'), ('ACC', 'Action'), ('THR', 'Thriller')], max_length=100)),
                ('age', models.IntegerField()),
                ('alive', models.BooleanField(default=True)),
            ],
        ),
    ]
