# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-06 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='category',
            field=models.CharField(choices=[('PYS', 'Psychological'), ('HIS', 'Historical'), ('ACC', 'Action'), ('SCI', 'Science'), ('GOT', 'Gothic'), ('ROM', 'Romance'), ('COM', 'Comic'), ('FIC', 'Fiction'), ('THR', 'Thriller'), ('FAN', 'Fantasy'), ('POL', 'Political'), ('ADV', 'Adventure'), ('CRM', 'Crime'), ('SAG', 'Saga'), ('HOR', 'Horror')], max_length=100),
        ),
    ]
