# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-06 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_auto_20170506_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='category',
            field=models.CharField(choices=[('ADV', 'Adventure'), ('THR', 'Thriller'), ('POL', 'Political'), ('SCI', 'Science'), ('HOR', 'Horror'), ('FIC', 'Fiction'), ('CRM', 'Crime'), ('ACC', 'Action'), ('FAN', 'Fantasy'), ('HIS', 'Historical'), ('PYS', 'Psychological'), ('ROM', 'Romance'), ('SAG', 'Saga'), ('GOT', 'Gothic'), ('COM', 'Comic')], max_length=100),
        ),
    ]
