# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-06 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_auto_20170506_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='category',
            field=models.CharField(choices=[('HIS', 'Historical'), ('ADV', 'Adventure'), ('SAG', 'Saga'), ('GOT', 'Gothic'), ('SCI', 'Science'), ('POL', 'Political'), ('FAN', 'Fantasy'), ('CRM', 'Crime'), ('ACC', 'Action'), ('PYS', 'Psychological'), ('ROM', 'Romance'), ('COM', 'Comic'), ('HOR', 'Horror'), ('FIC', 'Fiction'), ('THR', 'Thriller')], max_length=100),
        ),
    ]
